# USAGE
#
# try {
#     MapToml toml = MapToml.readToml(getAssets().open("testMap/map.toml"));
#     Log.i("TOML", toml.getType() == IMap.MapType.GOOGLE ? "GOOGLE" : "PICTURE");
#     Log.i("TOML", toml.getName());
#     Log.i("TOML", "" + toml.getDataSetCount());
#     Log.i("TOML", "" + toml.getDataSet(1).picture);
# } catch (IOException e) {
#     e.printStackTrace();
# }
#
# Output
#
# I/TOML: GOOGLE
# I/TOML: Test Map Pack
# I/TOML: 10
# I/TOML: berlin.jpg

name = "Test Map Pack"
type = "google-maps"

[meta-data]
map = "earth"

[[data-set]]
picture = "trondheim.jpg" #path to picture
latitude = 63.43 #north positive, south negative
longitude = 10.39 #east positive, west negative
description = "Third biggest city in Norway" #Optional

[[data-set]]
picture = "berlin.jpg"
latitude = 52.52
longitude = 13.4

[[data-set]]
picture = "rotenfels.jpg"
latitude = 49.82
longitude = 7.83

[[data-set]]
picture = "sydney.jpg"
latitude = -33.88
longitude = 151.21

[[data-set]]
picture = "liberty.jpg"
latitude = 40.69
longitude = -74.04

[[data-set]]
picture = "stpetersburg.jpg"
latitude = 59.94
longitude = 30.33

[[data-set]]
picture = "eiffeltower.jpg"
latitude = 48.86
longitude = 2.29

[[data-set]]
picture = "storebaelt.jpg"
latitude = 55.33
longitude = 10.97

[[data-set]]
picture = "miniaturwunderland.jpg"
latitude = 53.54
longitude = 9.99

[[data-set]]
picture = "tokyo.jpg"
latitude = 35.70
longitude = 139.74